---
title: "Quarto Playground"

execute:
  echo: true
  
format:
  html:
    theme: zephyr
    toc: true
    code-fold: true
    code-summary: "Show the code"
    
server: shiny
---

```{r}
#| include: false
#| echo: false
library(readr)
library(ggplot2)
library(dplyr)
library(shiny)

DATA_DIR <- if(Sys.getenv("DATA_DIR") != "") Sys.getenv("DATA_DIR") else "data/processed_gdpr"

questions <- readr::read_csv(here::here(DATA_DIR, "question_items_labelled.csv"))
question_chisq_df <- readr::read_rds(here::here("data",
                                                "processed",
                                                "question_chisq_df.rds"))

```


we can control the behaviour of the individual chunks with the [evaluation options](https://quarto.org/docs/computations/execution-options.html) (also globally in the header).

```{r}
#| label: fig-type
#| fig-cap: Figure caption
#| echo: false

ggplot(questions, aes(x = type_major))+
  geom_bar()

```

```{r}
#|include: true
selectInput('select_question',
            'Select Question',
            unique(question_chisq_df$subquestion_id))

plotOutput("plot")
```

```{r}
#| context: server
library(tidyverse)

question_chisq_df <- readr::read_rds(here::here("data",
                                                "processed",
                                                "question_chisq_df.rds"))

output$plot <- 
  renderPlot({
  df <- question_chisq_df %>%
    dplyr::filter(subquestion_id == input$select_question) %>%
    arrange(cramer_v) %>%    # First sort by val. This sort the dataframe but NOT the factor levels
    mutate(diversity_group = factor(diversity_group,
                                    levels = diversity_group))  # This trick update the factor levels
    ggplot(df, aes(x = diversity_group, y = cramer_v)) +
    geom_segment(aes(xend = diversity_group, yend = 0)) +
    geom_point(size = 4, color = "orange") +
    coord_flip() +
    labs(title = df$label_major.x[1],
         subtitle = df$label_major.y[1]) +
    theme_bw() +
    xlab("")
  
})
```


@fig-type shows the types of the questions.

# Formats to investigate

https://quarto.org/docs/output-formats/all-formats.html

## HTML
https://quarto.org/docs/reference/formats/html.html

many options!

## Quarto websites
https://quarto.org/docs/websites/


## Docusaurus
https://quarto.org/docs/output-formats/docusaurus.html
